### ISSUE TITLE
same padding 计算问题

### ISSUE THREAD

**Issue by FantDing** [GYee/CV_interviews_Q-A#32]
你好，按照 $ (h+2p-k)/s=h $ 公式计算出来的 $p=(sh+k-h)//2$  ,而代码中为什么是  $(self.stride  (h - 1) + k - h) // 2 $

**Comment by FantDing** [comment]
抱歉，应该是$ (h+2p-k)/s-1=h $

**Comment by GYee** [comment]
> 抱歉，应该是$ (h+2p-k)/s-1=h $

应该是$ [(h+2p-k)/s] + 1=h $

**Comment by FantDing** [comment]
对对，手误
