### ISSUE TITLE
clone后用Typora打开有公式显示问题，图片加载不出来

### ISSUE THREAD

**Issue by FishSmile-syx** [GYee/CV_interviews_Q-A#45]
我在win10系统下clone该项目，用Typora打开后，公式以及图片仍然加载不出来，有遇到这种情况的吗？
![image](https://user-images.githubusercontent.com/35222407/89701028-fb581700-d965-11ea-8e3b-518f53509570.png)
![image](https://user-images.githubusercontent.com/35222407/89701034-0612ac00-d966-11ea-9afc-90b332549522.png)

**Comment by GYee** [comment]
> 我在win10系统下clone该项目，用Typora打开后，公式以及图片仍然加载不出来，有遇到这种情况的吗？
> ![image](https://user-images.githubusercontent.com/35222407/89701028-fb581700-d965-11ea-8e3b-518f53509570.png)
> ![image](https://user-images.githubusercontent.com/35222407/89701034-0612ac00-d966-11ea-9afc-90b332549522.png)

公式加载不出来应该是因为你没设置好Typora的行内公式显示，百度设置下即可。图片的话确实可能有问题，你看看是否有图片的链接，复制都浏览器去看看能不能显示

**Comment by GYee** [comment]
> 我在win10系统下clone该项目，用Typora打开后，公式以及图片仍然加载不出来，有遇到这种情况的吗？
> ![image](https://user-images.githubusercontent.com/35222407/89701028-fb581700-d965-11ea-8e3b-518f53509570.png)
> ![image](https://user-images.githubusercontent.com/35222407/89701034-0612ac00-d966-11ea-9afc-90b332549522.png)

公式加载不出来应该是因为你没设置好Typora的行内公式显示，百度设置下即可。图片的话有点确实可能有问题，因为有的时候因为我这边的网络问题，没有成功上传到图床，但应该大部分是没有这问题的吧……
